bigday/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('wedding.urls')),
    url(r'^', include('guests.urls')),
    url(r'^admin/', admin.site.urls),
    url('^accounts/', include('django.contrib.auth.urls'))
]

guests/urls.py
from django.conf.urls import url

from guests.views import GuestListView, test_email, save_the_date, export_guests, \
        invitation, invitation_email_preview, invitation_email_test, rsvp_confirm, \
        dashboard, update_email_1, update_email_2, thank_you_email_preview

urlpatterns = [
    url(r'^guests/$', GuestListView.as_view(), name='guest-list'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^guests/export$', export_guests, name='export-guest-list'),
    url(r'^invite/(?P<invite_id>[\w-]+)/$', invitation, name='invitation'),
    url(r'^invite-email/(?P<invite_id>[\w-]+)/$', invitation_email_preview, name='invitation-email'),
    url(r'^invite-email-test/(?P<invite_id>[\w-]+)/$', invitation_email_test, name='invitation-email-test'),
    url(r'^save-the-date/$', save_the_date, name='save-the-date'),
    url(r'^update-email-1/$', update_email_1, name='update-email-1'),
    url(r'^update-email-2/$', update_email_2, name='update-email-2'),
    url(r'^email-test/(?P<template_id>[\w-]+)/$', test_email, name='test-email'),
    url(r'^rsvp/confirm/(?P<invite_id>[\w-]+)/$', rsvp_confirm, name='rsvp-confirm'),
    url(r'^thank-you-email/(?P<invite_id>[\w-]+)/$', thank_you_email_preview, name='thank-you-email'),
]

guests/models.py
from __future__ import unicode_literals
import uuid

from django.db import models
from django.dispatch import receiver

def _random_uuid():
    return uuid.uuid4().hex

class Party(models.Model):
    """
    A party consists of one or more guests.
    """
    name = models.TextField()
    save_the_date_sent = models.DateTimeField(null=True, blank=True, default=None)
    save_the_date_opened = models.DateTimeField(null=True, blank=True, default=None)
    invitation_id = models.CharField(max_length=32, db_index=True, default=_random_uuid, unique=True)
    invitation_sent = models.DateTimeField(null=True, blank=True, default=None)
    invitation_opened = models.DateTimeField(null=True, blank=True, default=None)
    is_invited = models.BooleanField(default=False)
    rehearsal_dinner = models.BooleanField(default=False)
    is_attending = models.BooleanField(null=True, default=None)
    thank_you_sent = models.DateTimeField(null=True, blank=True, default=None)
    send_thank_you = models.BooleanField(default=False)
    personal_message = models.TextField(null=True, blank=True)
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return 'Party: {}'.format(self.name)

    @classmethod
    def in_default_order(cls):
        return cls.objects.order_by('-is_invited', 'name')

    @property
    def ordered_guests(self):
        return self.guest_set.order_by('is_child', 'pk')

    @property
    def any_guests_attending(self):
        return any(self.guest_set.values_list('is_attending', flat=True))

    @property
    def guest_emails(self):
        return list(filter(None, self.guest_set.values_list('email', flat=True)))


class Guest(models.Model):
    """
    A single guest
    """
    party = models.ForeignKey('Party', on_delete=models.CASCADE)
    first_name = models.TextField()
    last_name = models.TextField(null=True, blank=True)
    email = models.TextField(null=True, blank=True)
    is_attending = models.BooleanField(null=True, default=None)
    attending_braai = models.BooleanField(null=True, default=None)
    needs_accomodation = models.BooleanField(null=True, default=None)
    dietary_restrictions = models.CharField(max_length=50, null=True, blank=True)
    is_child = models.BooleanField(default=False)

    @property
    def name(self):
        return u'{} {}'.format(self.first_name, self.last_name).strip()

    @property
    def unique_id(self):
        # convert to string so it can be used in the "add" templatetag
        return str(self.pk)

    def __str__(self):
        return 'Guest: {} {}'.format(self.first_name, self.last_name)

guests/forms.py
from django import forms
from .utils import OptionalChoiceField
from .models import Guest

YES_NO_CHOICES = (
    (True, 'Yes'),
    (False, 'No'),
)

DIETARY_RESTRICTION_CHOICES = (
    ('none', 'None'),
    ('vegetarian', 'Vegetarian'),
    ('vegan', 'Vegan'),
    ('white', 'No red meat'),
    ('other', 'Other'),
)


class IndividualRSVPForm(forms.Form):
    guest_name = forms.CharField(required=False,
                                 label='Guest name (if different)',
                                 widget=forms.TextInput(attrs={
                                     'class': 'guest-name-field form-input'
                                 }))
    is_attending = forms.ChoiceField(choices=YES_NO_CHOICES,
                                     required=False,
                                     widget=forms.RadioSelect(attrs={
                                         'class': 'attending-radio form-check-input'
                                     }))
    dietary_restrictions = OptionalChoiceField(required=False,
                                               choices=DIETARY_RESTRICTION_CHOICES)
    needs_accomodation = forms.ChoiceField(choices=YES_NO_CHOICES,
                                           required=False,
                                           widget=forms.RadioSelect())
    attending_friday_braai = forms.ChoiceField(choices=YES_NO_CHOICES,
                                               required=False,
                                               widget=forms.RadioSelect())
    guest_id = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'hidden-field form-input'
    }))

    def __init__(self, *args, guest_index, party, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['guest_id'].initial = party[guest_index].pk
        self.guest = party[guest_index]

    def clean(self):
        is_attending = self.cleaned_data['is_attending']

        if is_attending == 'True' or is_attending == '':
            if self.cleaned_data['is_attending'] == '':
                self.add_error('is_attending', 'This field is required')
            if self.cleaned_data['needs_accomodation'] == '':
                self.add_error('needs_accomodation', 'This field is required')
            if self.cleaned_data['attending_friday_braai'] == '':
                self.add_error('attending_friday_braai', 'This field is required')
            guest_id = self.cleaned_data['guest_id']
            guest_name = self.cleaned_data['guest_name']
            guest = None
            try:
                guest = Guest.objects.get(pk=guest_id)
            except Guest.DoesNotExist:
                raise forms.ValidationError('Guest not found')
            if guest.name == 'Guest' and guest_name == '':
                self.add_error('guest_name', 'This field is required')
        return self.cleaned_data


class RSVPFormset(forms.BaseFormSet):
    def get_form_kwargs(self, index):
        kwargs = super().get_form_kwargs(index)
        kwargs['guest_index'] = index
        return kwargs

guests/views.py
import base64
from collections import namedtuple
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.urls import reverse
from django.db.models import Count, Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import ListView
from guests import csv_import
from guests.invitation import get_invitation_context, INVITATION_TEMPLATE, \
        guess_party_by_invite_id_or_404, send_invitation_email
from guests.models import Guest, Party
from guests.save_the_date import get_save_the_date_context, \
        send_save_the_date_email, SAVE_THE_DATE_TEMPLATE, \
        SAVE_THE_DATE_CONTEXT_MAP
from guests.forms import IndividualRSVPForm, RSVPFormset
from guests import emails, thankyou


class GuestListView(ListView):
    model = Guest


@login_required
def export_guests(request):
    export = csv_import.export_guests()
    response = HttpResponse(export.getvalue(), content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=all-guests.csv'
    return response


@login_required
def dashboard(request):
    parties_with_pending_invites = Party.objects.filter(
        is_invited=True, is_attending=None
    ).order_by('name')
    parties_with_unopen_invites = parties_with_pending_invites.filter(invitation_opened=None)
    parties_with_open_unresponded_invites = parties_with_pending_invites.exclude(invitation_opened=None)
    attending_guests = Guest.objects.filter(is_attending=True)
    guests_without_meals = attending_guests.filter(
        is_child=False
    ).filter(
        Q(dietary_restrictions__isnull=True) | Q(dietary_restrictions='')
    ).order_by('first_name')
    meal_breakdown = attending_guests.exclude(dietary_restrictions=None).values('dietary_restrictions').annotate(count=Count('*'))
    return render(request, 'guests/dashboard.html', context={
        'guests': Guest.objects.filter(is_attending=True).count(),
        'possible_guests': Guest.objects.filter(party__is_invited=True).exclude(is_attending=False).count(),
        'not_coming_guests': Guest.objects.filter(is_attending=False).count(),
        'pending_invites': parties_with_pending_invites.count(),
        'pending_guests': Guest.objects.filter(party__is_invited=True, is_attending=None).count(),
        'guests_without_meals': guests_without_meals,
        'parties_with_unopen_invites': parties_with_unopen_invites,
        'parties_with_open_unresponded_invites': parties_with_open_unresponded_invites,
        'unopened_invite_count': parties_with_unopen_invites.count(),
        'total_invites': Party.objects.filter(is_invited=True).count(),
        'meal_breakdown': meal_breakdown,
    })

def invitation(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    if party.invitation_opened is None:
        # update if this is the first time the invitation was opened
        party.invitation_opened = timezone.now()
        party.save()
    guests = party.ordered_guests.all()
    RSVPForm = formset_factory(IndividualRSVPForm,
                               extra=party.ordered_guests.count(),
                               formset=RSVPFormset)
    if request.method == 'POST':
        formset = RSVPForm(request.POST, form_kwargs={'party': guests})
        if formset.is_valid():
            for form in formset.cleaned_data:
                guest = party.guest_set.get(pk=form['guest_id'])
                guest.is_attending = form['is_attending']
                guest.needs_accomodation = form['needs_accomodation']
                guest.attending_braai = form['attending_friday_braai']
                guest.dietary_restrictions = form['dietary_restrictions'].lower()
                if form['guest_name'] != '':
                    name = form['guest_name'].split(' ')
                    guest.first_name = name[0]
                    guest.last_name = ' '.join(name[1:]).strip()
                guest.save()
            party.is_attending = party.any_guests_attending
            party.save()
            return HttpResponseRedirect(reverse('rsvp-confirm', args=[invite_id]))
    else:
        formset = RSVPForm(form_kwargs={'party': guests})
    return render(request, template_name='guests/invitation.html', context={
        'bride_and_groom': settings.BRIDE_AND_GROOM,
        'formset': formset,
    })

def rsvp_confirm(request, invite_id=None):
    party = guess_party_by_invite_id_or_404(invite_id)
    return render(request, template_name='guests/rsvp_confirmation.html', context={
        'party': party,
        'support_email': settings.DEFAULT_WEDDING_REPLY_EMAIL,
        'bride_and_groom': settings.BRIDE_AND_GROOM,
    })


def invitation_email_preview(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    context = get_invitation_context(party)
    return render(request, INVITATION_TEMPLATE, context=context)


@login_required
def invitation_email_test(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    send_invitation_email(party, recipients=[settings.DEFAULT_WEDDING_TEST_EMAIL])
    return HttpResponse('sent!')

def save_the_date(request):
    context = get_save_the_date_context()
    context['email_mode'] = False
    return render(request, SAVE_THE_DATE_TEMPLATE, context=context)

def update_email_1(request):
    context = emails.get_context()
    context['email_mode'] = False
    return render(request, emails.EMAIL_TEMPLATE.format(template='details'),
                  context=context)

def update_email_2(request):
    context = emails.get_context()
    context['email_mode'] = False
    return render(request, emails.EMAIL_TEMPLATE.format(template='livestream'),
                  context=context)

@login_required
def test_email(request, template_id):
    context = get_save_the_date_context()
    send_save_the_date_email(context, [settings.DEFAULT_WEDDING_TEST_EMAIL])
    return HttpResponse('sent!')


def _base64_encode(filepath):
    with open(filepath, "rb") as image_file:
        return base64.b64encode(image_file.read())

def thank_you_email_preview(request, invite_id):
    party = guess_party_by_invite_id_or_404(invite_id)
    context = emails.get_context()#.update(thankyou.get_context(party))
    extra_context = thankyou.get_context(party)
    context.update(extra_context)
    return render(request, thankyou.EMAIL_TEMPLATE, context=context)

guests/templates/guests/dashboard.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="container" id="main">
        <h1>Dashboard</h1>
        <table class="table table-striped">
            <tr>
                <td>Guests Attending / Possible</td>
                <td>{{ guests }} / {{ possible_guests }}</td>
            </tr>
            <tr>
                <td>Pending Invitations</td>
                <td>{{ pending_invites }} ({{ pending_guests }} guests)</td>
            </tr>
            <tr>
                <td>Unopened Invitations</td>
                <td>{{ unopened_invite_count }}<span class="text-muted"> / {{ total_invites }}</span></td>
            </tr>
            <tr>
                <td>Not Coming</td>
                <td>{{ not_coming_guests }}</td>
            </tr>
            </tbody>
        </table>
        <div class="row">
            <div class="col-lg-12">
                <h1>Meal choices</h1>
                <table class="table">
                    <thead>
                        <tr>
                            {% for meal in meal_breakdown %}
                            <th>{{ meal.dietary_restrictions | title }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% for meal in meal_breakdown %}
                            <td>{{ meal.count }}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <h1>Unopened Invitations</h1>
                {% with party_list=parties_with_unopen_invites %}
                    {% include "guests/partials/party_list.html" %}
                {% endwith %}
            </div>
            <div class="col-lg-6">
                <h1>Open Unresponded Invitations</h1>
                {% with parties_with_open_unresponded_invites as party_list %}
                    {% include "guests/partials/party_list.html" %}
                {% endwith %}
            </div>
        </div>
        <div class="col-lg-6">
                <h1>Attending Guests Without Meals</h1>
                {% with guest_list=guests_without_meals %}
                    {% include "guests/partials/guest_list.html" %}
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock %}

guests/templates/guests/invitation.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block page_head %}
<link href="{% static 'bigday/css/invitation.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block page_content %}
<div class="container" id="invitation-body">
  <section class="img-container">
  </section>
  <section class="col-md-6 text-center">
    <div id="invitation-details">
      <h2>The Wedding of {{ bride_and_groom }}</h2>
      <p class="lead">
      10 April 2021 at 16:00<br>
      De Uijlenes<br>
      Gaansbaai
      </p>
    </div>
  </section>
  <section class="col-md-6">
    {% bootstrap_formset_errors formset %}
    <form data-toggle="validator" id="invitation-details" class="form-horizontal" method="post">
      <h2 id="rsvp-header" class="text-center">RSVP</h2>
      <div class="rsvp-form">
        <hr class="guest-seperator">
        {{ formset.management_form }}
        {% csrf_token %}
        {% for form in formset %}
        <div class="form-group row">
          <label class="col-md-3 col-form-label" for="guest_name">Guest:</label>
          <p class="col-md-9 form-control-static" id="guest_name">{{ form.guest.name }}</p>
        </div>
        {% bootstrap_form form layout='horizontal'%}
        <hr class="guest-seperator">
        {% endfor %}
        {% buttons submit='Submit' %}{% endbuttons %}
      </div>
    </form>
  </section>
</div>
{% endblock %}
{% block page_js %}
<script src="{% static 'validator.js' %}"></script>
<script>
  $(function () {
    var updateSelection = function(elements, disable) {
        for (var i = 0; i < elements.length; i++) { 
          elements[i].disabled = disable;
          if (disable) {
            elements[i].checked = false;
          }
        }
    }

    var updateDietaryRequirements = function(e) {
      var target = $(e.target);
      var value = target.val();
      var dietaryInput = target.next('input');

      if (value === 'other') {
        updateSelection(dietaryInput, false);
      } else {
        updateSelection(dietaryInput, true);
      }
      // reload validation
      $(document.forms[0]).validator('destroy');
      $(document.forms[0]).validator();
    }

    var updateForm = function(e) {
      var target = $(e.target);
      var value = target.attr('value');

      var mealButtonContainer = target.closest('.form-group').next('.form-group');
      var accomodationContainer = mealButtonContainer.next('.form-group');
      var braaiContainer = accomodationContainer.next('.form-group');
      var dietaryOptions = mealButtonContainer.find('select');
      var dietaryInput = mealButtonContainer.find('input');
      var accomodationOptions = accomodationContainer.find('input');
      var braaiOptions = braaiContainer.find('input');
      if (value === 'True') {
        updateSelection(dietaryOptions, false);
        updateSelection(accomodationOptions, false);
        updateSelection(braaiOptions, false);
        updateDietaryRequirements({'target': dietaryOptions});
      } else if (value === 'False') {
        updateSelection(dietaryOptions, true);
        updateSelection(dietaryInput, true);
        updateSelection(accomodationOptions, true);
        updateSelection(braaiOptions, true);
      }
    }

    $('input.attending-radio').change(updateForm);
    $('.optional-choice-select').change(updateDietaryRequirements);

    $(document).ready(function() {
      var elements = $('.hidden-field').closest('.form-group');
      for (var i = 0; i < elements.length; i++) {
          elements[i].hidden = true;
      }
      elements = $('input.attending-radio')
      for (var i = 0; i < elements.length; i++) {
        if (elements[i].checked) {
          updateForm({'target': elements[i]});
        }
      }
      var elements = $('.optional-choice-select')
      for (var i = 0; i < elements.length; i++) {
        updateDietaryRequirements({'target': elements[i]});
      }
    });
  });
</script>
{% endblock %}

guests/templates/guests/rsvp_confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block page_head %}
    <link href="{% static 'bigday/css/rsvp-confirmation.css' %}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block page_content %}
    <div class="layer"></div>
    <div class="container" id="main">
        <h2>Hi {{ party.name }}! Thanks for your response!</h2>
        {% if party.any_guests_attending %}
            <p>
                We can't wait to celebrate with you at De Uijlenes!
            </p>
            <p>
                If you have any other questions, don't hesitate to email us at
                <a href="mailto:{{ support_email }}">{{ support_email }}</a>.
            </p>
        {% else %}
            <p>
                We're sorry you won't be able to join us at De Uijlenes.
            </p>
            <p>
                We look forward to catching up with you some other time!
            </p>
        {% endif %}
        <p>
          - {{ bride_and_groom }}
        </p>
    </div>
{% endblock %}